### ISSUE TITLE
CdmiInputStream should handle null metadata case

### ISSUE THREAD

**Issue by julien101** [scality/CaDMIum#3]
There might be a case where metadata is null, and inputstream not able to handle it. 
A specific test case should cover this point.

Resolution proposed by cdruine in https://github.com/scality/CaDMIum/issues/1

``` java
if(meta==null) 
    this.final_pos=0; // thrown an exception instead ? 
else{ ... }
```

**Comment by ziadbizri** [comment]
Thanks for pointing out that the metadata could be null. This is a very special case in which we are not getting the metadata for a file or a container (maybe a pabaility?). In any case, we should never return null and raise an exception instead.
