### ISSUE TITLE
Need more flexibility on CdmiMetadata

### ISSUE THREAD

**Issue by julien101** [scality/CaDMIum#4]
As reported by cdruine in https://github.com/scality/CaDMIum/issues/1

The issue is that we don't know all the fields (user one...), so i made a json explorer for all objects (unknown in a user map accessible) , spec. the Acls (even if they are not real) , guid, uid ...
For direct access to JSon data: 

``` java
public class CdmiMetadata { 
    private final JsonNode root; 
    public Object getUnderlyingObject() //return an object if you change your struct... {
        return root; 
    } 
    // ... and in constructor 
    root = m.readTree(parser); //use that private field. 
```

-- And inside a crawler i add a childs name retrieve to apply names filters (bonus:your names rule "ended by / is a container".)

**Comment by ziadbizri** [comment]
The class CdmiMetadata should not be used directly, it is under com.scality.cdmi.impl.metadata. Instead it is better to add to the FileMetadata interface the original metadata string and let the user parse it if needed.
